package sk.nixone.ds.core;

/**
 * Generator for creating multiple random sequences. Should be only one in a system that internally depends on the indepence of the
 * values generated by multiple random sequences.
 * 
 * @author nixone
 *
 */
public class Randoms
{
	private Random seedGenerator;
	
	/**
	 * Creates a generator with seed from system time
	 */
	public Randoms() {
		seedGenerator = new Random();
	}
	
	/**
	 * Creates a generator with supplied seed
	 * @param seed seed
	 */
	public Randoms(long seed) {
		seedGenerator = new Random(seed);
	}
	
	/**
	 * Creates a new random sequence that is statistically considered independent of the others generated from this generator.
	 * @return new random sequence
	 */
	public Random getNextRandom() {
		return new Random(seedGenerator.nextLong());
	}
}
